### ISSUE TITLE
webstart fails for user names with german umlauts

### ISSUE THREAD

**Issue by btreut** [ojdkbuild/ojdkbuild#103]
Trying to start a JNLP file via FireFox (i.e., download & open) does not work on MS-Windows, if the username contains german umlauts. It fails with:
"netx: Invalid jnlp file C:\Users\G?nd?z\Downloads\qisfsv3t.jnlp"
here the user name was "Gündüz". See also: [javaws_last_log.txt](https://github.com/ojdkbuild/ojdkbuild/files/3711308/javaws_last_log.txt)
Tested on another system with a new user "Täst" results in almost the same behavior:
"netx: Invalid jnlp file C:\Users\T?st\Downloads\qisfsv3t.jnlp" (javaws_last_log.txt can be provided if necessary). 

PS: I hope this is the right place to file the issue, if not, please guide me where to file it.

**Comment by hendrikebbers** [comment]
Hi @btreut this looks like an issue in IcedTeaWeb. Can you open an issue at https://github.com/AdoptOpenJDK/IcedTea-Web (and link this issue).

**Comment by ojdkbuild** [comment]
Thanks for the report! I will look into this (it looks similar to #84), but cannot promise a fix in 8u232 - it is very close to its release now.

As hendrikebbers wrote, it may be a good idea to bring it to `AdoptOpenJDK/IcedTea-Web` (that you've obviously already done), where the main development of IcedTea-Web itself is done. I can cherry-pick fixes from there for the ojdkbuild builds.

**Comment by ojdkbuild** [comment]
This appeared to be a problem in launcher, that generally treats all paths with respect to unicode, but was using incorrect non-unicode version of user-specified command line. [Fixed](https://github.com/ojdkbuild/contrib_itw-launcher/commit/50663774660aadd274170da52794ab3ac49f02ef) that and it is included into upcoming 8u232.

The fix slightly changes the behaviour (should not affect JNLP applications), previously only arguments with spaces were quoted (if these quotes are included in input command line). Now all arguments are quoted, so instead of:

    foo "bar baz" boo

launcher now passes to ITW:

    "foo" "bar baz" "boo"

If you'd like to try the fixed version of launcher - uploaded it here: [javaws.zip](https://github.com/ojdkbuild/ojdkbuild/files/3734111/javaws.zip).

**Comment by btreut** [comment]
thanks. I cannot test it in the moment, I'm on the leave for two weeks off ...

**Comment by ojdkbuild** [comment]
Fixed in 8u232, closing the issue, please reopen if problem persists.
