### ISSUE TITLE
Installer text is difficult to read when using high contrast theme on Windows 10

### ISSUE THREAD

**Issue by Zulgrib** [ojdkbuild/ojdkbuild#23]
First and last installer's window text is almost impossible to read (white and light grey) when using high contraste theme on Win10.

**Comment by ojdkbuild** [comment]
Hi, thanks for the report! The problem is clear (attaching examples), but it's currently not clear how to fix it and not to break a default view at the same time. I'll leave this issue open and will return to it after 8u161 update.

default
![default](https://user-images.githubusercontent.com/17926585/34739950-d9357c0c-f575-11e7-8997-a1bb59080746.png)
high contrast 1
![hc1](https://user-images.githubusercontent.com/17926585/34739951-d9730284-f575-11e7-9b28-cbe62d75e8d8.png)
high contrast 2
![hc2](https://user-images.githubusercontent.com/17926585/34739952-d99979d2-f575-11e7-9916-abfc25cad156.png)
high contrast 3
![hc3](https://user-images.githubusercontent.com/17926585/34739953-d9b55ecc-f575-11e7-8167-4e262053f410.png)
high contrast 4
![hc4](https://user-images.githubusercontent.com/17926585/34739954-d9cf52a0-f575-11e7-9a0b-21b0d02f4824.png)

**Comment by ojdkbuild** [comment]
I experimented a bit with high contrast setting and other installers of popular tools:

![hc1_cmake](https://user-images.githubusercontent.com/17926585/36552306-65df0bf0-17ae-11e8-90a3-72f1a38a4255.png)
![hc1_node](https://user-images.githubusercontent.com/17926585/36552332-76340316-17ae-11e8-83e5-cb92d94fc36e.png)
![hc1_vagrant](https://user-images.githubusercontent.com/17926585/36552340-7966c690-17ae-11e8-8399-aefc2f0872ac.png)

 Generally all of them have the same problem - to look nice, main background needs to be set to white. But there is no way to hook in high contrast support from OS for this background, as it is supplied to installer as a BMP image. So it stays white with any theme. And I am reluctant changing it to non-white.

As a workaround, the font color in theme settings may be changed from yellow (for high contrast 1 theme) to some other color, that can be read on both black and white backgrounds:

![hc_settings](https://user-images.githubusercontent.com/17926585/36552561-009d5dfe-17af-11e8-9b6b-d44d9d8f42a7.png)

**Comment by Yousha** [comment]
@ojdkbuild BTW, it is High Contrast, not dark theme...
Which is completely different
it also affects Web page components...
