### ISSUE TITLE
Windows - association with .jar file is missing

### ISSUE THREAD

**Issue by Yousha** [ojdkbuild/ojdkbuild#33]
When installing OpenJDK on Windows, the installer does not configure .jar association in Windows. 
So we cannot launch a jar file from the explorer (just by cmd)

openjdk version "1.8.0_161-1-ojdkbuild"
OpenJDK Runtime Environment (build 1.8.0_161-1-ojdkbuild-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)
Windows 7 64bit

**Comment by ojdkbuild** [comment]
Hi, the installer currently brings as little as possible OS env changes with its default component ("jdk"). Even `JAVA_HOME` is not set. But the feature for double-clicking the JARs sounds like a nice **optional** feature. I'll leave this issue open for now, perhaps it makes sense to move all env-adjusting features into separate MSI component(s).

**Comment by AntumDeluge** [comment]
OpenJDK should be configured to run .jar files after installation. That is the behavior on most Linux systems & should be on Windows as well. People who, after installing OpenJDK, cannot figure out how to run .jar files with it will quickly revert back to Oracle Java, as Oracle's installer configures the association automatically.

Right-clicking on .jar & selecting "open with" is not enough either. Because it will simply try to run `java foo.jar`, which will result in failure without any error information presented. Currently, in order to configure correctly, one must manually edit file associates & change the command to `"\path\to\javaw.exe" -jar "%1"`. And on Windows Vista & above a third-party app is required to make changing file associations easier.

So, I think the installer should definitely configure OpenJDK as the default Java for opening .jar files.

```
> java -version
openjdk version "1.8.0_171-1-ojdkbuild"
OpenJDK Runtime Environment (build 1.8.0_171-1-ojdkbuild-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
```

**Comment by ojdkbuild** [comment]
Optional `*.jar` association is included with 8u191 installer. Double click in Explorer and right-click + Launch is supported. Closing the issue, please reopen on any problems (this kind of integration is non-trivial to test).

**Comment by Misterodd** [comment]
Its now "Executable Jar File" as a filetype in Windows 10.
do it via the Types Program or via this reg file:
``Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\jarfile]
@="Executable Jar File"

[HKEY_CLASSES_ROOT\jarfile\shell]

[HKEY_CLASSES_ROOT\jarfile\shell\open]

[HKEY_CLASSES_ROOT\jarfile\shell\open\command]
@="\"C:\\Program Files\\Java\\OpenJDK\\jdk-13\\bin\\javaw.exe\" -jar \"%1\""
``
the last line is the PATH to your jdk. Beware of the \\ to escape the backslash.
safe this code to a Registryfile like openWithOpenJDK-jarfile.reg

WARNING! as the tool above, this alters the Windows Registry, that should work, but could broke.

Now you can copy this to every win-pc you want.
