### ISSUE TITLE
Update code for x64 and x86

### ISSUE THREAD

**Issue by afischer-opentext-com** [ojdkbuild/ojdkbuild#37]
Hi, 

I have a use case which requires me install the x64 and x86 flavor of the OpenJDK. This is to my understanding mainly blocked by a hard wired [update code in here](https://github.com/ojdkbuild/ojdkbuild/blob/master/src/java-1.8.0-openjdk/CMakeLists.txt#L39). 
The same update code for x86 and x64 leads to the situation that the MSIs holding the different architecture update (and remove) the other architecture. 

What is your feeling with that? Would a PR, which attempts to have this independently setup, have any change to be accepted?

alex

**Comment by ojdkbuild** [comment]
Hi,

Yes, I think it is a good idea to have different MSI guids for x86_64 and x86 installers. I will use different guids for next release (planned at the end of July). I think `-Dopenjdk_INSTALLER_PRODUCT_UUID=... -Dopenjdk_INSTALLER_UPDATE_UUID=...` cmake args should be enough - so no need for PR. Also in such configuration (with both MSIs) WebStart and Update Notifier should not be installed - they will use the same working dirs.

Please note, that 32-bit MSI was built as an afterthought (mostly to [allow using WebStart on win-x86](https://github.com/ojdkbuild/ojdkbuild/issues/2#issuecomment-342361295)) and had little testing. There is a 32-bit-only problem with Update Notifier (uninstall broken) I suggest avoiding it in current version.

**Comment by afischer-opentext-com** [comment]
That should work out. Thank you very much!

**Comment by ojdkbuild** [comment]
Changed update code for 32-bit MSI in [8u181 release](https://github.com/ojdkbuild/ojdkbuild/releases/tag/1.8.0.181-1). Because of this 32-bit MSI cannot be updated automatically from 8u171 to 8u181, but that allows parallel installation of 64-bit and 32-bit installers.

Please note, code inside 10.0.2 MSI is not changed - decided that is would be too confusing to not allow to update from 10.0.1 to 10.0.2, and jdk10 is EOL anyway. Going to use different keys for jdk11.
