### ISSUE TITLE
FR: add auto-updater to msi builds

### ISSUE THREAD

**Issue by GitMensch** [ojdkbuild/ojdkbuild#39]
*I do wonder why I didn't see any reference to this topic yet, maybe I've not seen something and it can be directly closed...*

It would be nice to be *optionally* able to use an auto-update mechanism like Oracle Java SE has, maybe polling the repo https://developer.github.com/v3/repos/releases/, querying the matching Java version and if it is newer download the artifact (depending on the user's setting).

The missing updater was the reason for "No, we don't use OpenJDK builds but Oracle Java; people are more likely to accept an update when prompted then to manually replace an existing version".

**Comment by ojdkbuild** [comment]
[Update Notifier](https://github.com/ojdkbuild/contrib_update-notifier) is included with x86_64 MSI, it periodically checks descriptor from [here](https://github.com/ojdkbuild/ojdkbuild/blob/master/resources/update/java-1.8.0-openjdk.windows.x86_64.version.json) and displays a Windows tray message on a user login if new jdk version appeared.

It has the following limitations:

1. updater does not actually download the new version of jdk - instead browser windows is opened with [this link](https://github.com/ojdkbuild/ojdkbuild#downloads-for-windows-x86_64)

2. notification inside the windows tray is not persistent - after it expires (timeout depends on windows settings and desktop activity - usually about 15 seconds) it is removed from tray. As a result, the UX interaction may look more or less the same as the one from [this picture](http://i.imgur.com/fzW80.jpg). The reason for this was the inconsistent behaviour of windows tray (and notification center on win10) between windows versions.

Check period can be tuned inside Windows Task Scheduler.

**Comment by GitMensch** [comment]
@ojdkbuild I may missed this, but why isn't the update notifier included in the windows.x86.msi ?

**Comment by ojdkbuild** [comment]
32-bit installer build was added as an afterthought and mostly to support WebStart shell integration for 32-bit installs. Updater needs to be generalized a bit to be used with 32-bit MSI, for example download link from it points to 64-bit MSI. Also It appeared that while other parts of MSI works fine on 32-bit (on both 32-bit and 64-bit OS), updater uninstall actions cause problems on 32-bit. It appeared to be easier to remove it from 32-bit installer, as before this issue there were no user interest in updater.

**Comment by btreut** [comment]
> as before this issue there were no user interest in updater

although this issue is closed, I think I comment on it since at least I am quite interested in the functionality of an update notfiier. It is/was the last point, which I missed when I compare OpenJDK and Oracle JDK. I don't know of any other place to show my interest.

**Comment by ojdkbuild** [comment]
Please free to re-open, if you have some suggestions for the Update Notifier.

Currently UN consists of two utilities (both are triggered by system Task Scheduler):

 - checker: downloads JSON update descriptor ([example](https://github.com/ojdkbuild/ojdkbuild/blob/master/resources/update/java-1.8.0-openjdk.windows.x86_64.version.json)) and saves it to the local directory. This utility is pretty much complete, it is doing its job, it also downloads resource in streaming manner (the same method can be used to download actual updated MSI).

 - notifier: reads the JSON descriptor and compares a version number from it with the version number embedded in this version of notifier. Displays system tray notification, if descriptor has a newer version. This utility is of limited usefulness, because it cannot actually download the updated MSI it is notifying about. It was written for Red Hat builds which cannot be downloaded without login. And integrating RH DevPortal login capabilities into it appeared to be impractical.

Thus for some customized installations Update Notifier can be used effectively the following way:

1. use checker as is, possibly pointing it to some other place for JSON update descriptor and configuring its Task Scheduler job as required

2. use a custom script (batch+curl, powershell, python etc) with Task Scheduler, that can periodically check the downloaded JSON to find out whether the version was updated and then download the required MSI and run "msiexec" for it with required parameters

It is well possible to implement a "universal" GUI utility for the second task, that would present a user-friendly form to download MSI from publicly available URL and run its installer (or install silently). But this task is not funded by Red Hat (no public direct URLs from RH to download), thus this utility currently exists as "notifier-only".
