### ISSUE TITLE
macOS Build

### ISSUE THREAD

**Issue by gamma** [ojdkbuild/ojdkbuild#44]
I can see that there is only Windows in this repository and that there are other repos for Linux. Is there going to be a build for macOS as well?

Also: does the Linux build work with Alpine?

Thanks!

**Comment by ojdkbuild** [comment]
Hi, sorry for delay, checked Alpine compat, it works but requires [glibc to be installed](https://github.com/sgerrand/alpine-pkg-glibc/issues/1), I was able to build and run Spring Boot example installing glibc this way:

    apk --no-cache --allow-untrusted -X https://apkproxy.herokuapp.com/sgerrand/alpine-pkg-glibc add glibc glibc-bin

Separate build need to be done to support musl libc directly, and there are no plans to add such builds to this project.

Some additional libs may be required for headful mode (haven't tried it) and `freetype` is required for font related things. Freetype can be bundled I think, going to revisit it, filed #46 .

About MacOS, generally the answer is "no" (see also #17 ) because for a long time it was expected, that nobody will support Mac in jdk8 after it's Oracle EOL. But recently projected new lead of jdk8-updates project [mentioned Mac](http://mail.openjdk.java.net/pipermail/jdk-dev/2018-September/001913.html) so it possibly may be added. I leave the issue open for some time and update it with info about Mac.

**Comment by ojdkbuild** [comment]
Current answer about the macOS OpenJDK 8 builds in this project is "no", it may be overridden in future, but that is unlikely (I'll reopen the issue if that happens). As an alternative, I can suggest using [macOS builds from AdoptOpenJDK](https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot#x64_mac).
